name: ex_widget
description: A new Flutter package project.
version: 0.1.0
publish_to: none

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  ex_module_core:
    git:
      url: https://github.com/DoTungLam96/ex_module_core.git
      ref: main
  flutter_svg: 1.1.5
  fluttertoast: ^8.0.9
  showcaseview: ^2.0.3
  introduction_screen: ^3.1.8
  calendar_date_picker2: ^0.2.8
  just_the_tooltip: ^0.0.12
  flutter_slidable: ^1.0.0

  cached_network_image:
  auto_size_text: ^3.0.0

  flutter_svg_provider: ^1.0.3

  fl_chart: ^0.62.0

dev_dependencies:
  build_runner: ^2.1.4
  flutter_gen_runner: ^5.3.1

flutter:
  assets:
    - assets/images/
  uses-material-design: false

  fonts:
    - family: SF-UI-Display
      fonts:
        - asset: assets/fonts/SF-UI-Display-Thin.otf
          weight: 100
        - asset: assets/fonts/SF-UI-Display-Ultralight.otf
          weight: 200
        - asset: assets/fonts/SF-UI-Display-Light.otf
          weight: 300
        - asset: assets/fonts/SF-UI-Display-Regular.otf
          weight: 400
        - asset: assets/fonts/SF-UI-Display-Medium.otf
          weight: 500
        - asset: assets/fonts/SF-UI-Display-Semibold.otf
          weight: 600
        - asset: assets/fonts/SF-UI-Display-Bold.otf
          weight: 700
        - asset: assets/fonts/SF-UI-Display-Black.otf
          weight: 800
        - asset: assets/fonts/SF-UI-Display-Heavy.otf
          weight: 900
